In [1]:
from google.colab import files
uploaded = files.upload()

Saving weather_data2.csv to weather_data2.csv

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("weather_data2.csv")
df

          day temperature windspeed     event
0  01/01/2017        32 F     6 mph      Rain
1  01/02/2017      -99999     7 mph     Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017        32 C    -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [7]:
# Replace -99999 with NaN values :

new_df = df.replace(-99999,np.NaN)
new_df

          day temperature windspeed     event
0  01/01/2017        32 F     6 mph      Rain
1  01/02/2017      -99999     7 mph     Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017        32 C    -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [8]:
 df

          day temperature windspeed     event
0  01/01/2017        32 F     6 mph      Rain
1  01/02/2017      -99999     7 mph     Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017        32 C    -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [9]:
new_df1 = df.replace({
    "temperature" : -99999,
    "windspeed" : -99999
},np.NaN)

new_df1

          day temperature windspeed     event
0  01/01/2017        32 F     6 mph      Rain
1  01/02/2017      -99999     7 mph     Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017        32 C    -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [10]:
new_df

          day temperature windspeed     event
0  01/01/2017        32 F     6 mph      Rain
1  01/02/2017      -99999     7 mph     Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017        32 C    -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [13]:
new_df = df.replace({
    -99999 : np.NaN,
    "No Event" : "Sunny"
})

new_df

          day temperature windspeed  event
0  01/01/2017        32 F     6 mph   Rain
1  01/02/2017      -99999     7 mph  Sunny
2  01/03/2017          28    -99999   Snow
3  01/04/2017      -99999         7  Sunny
4  01/05/2017        32 C    -99999   Rain
5  01/06/2017          31         2  Sunny
6  01/06/2017          34         5  Sunny

In [14]:
# Remove the units infornt of values:

new_df = df.replace("[A-Za-z]",'',regex=True)
new_df

          day temperature windspeed event
0  01/01/2017         32         6
1  01/02/2017      -99999        7
2  01/03/2017          28    -99999
3  01/04/2017      -99999         7
4  01/05/2017         32     -99999
5  01/06/2017          31         2
6  01/06/2017          34         5

In [15]:
# observe the above df the event column is empty because all values in that column are letters

In [17]:
# Lets change this using Dictionary :

new_df = df.replace({
    "temperature" : "[A-Za-z]",
    "windspeed" : "[A-Za-z]"
},'',regex=True)

new_df

          day temperature windspeed     event
0  01/01/2017         32         6       Rain
1  01/02/2017      -99999        7      Sunny
2  01/03/2017          28    -99999      Snow
3  01/04/2017      -99999         7  No Event
4  01/05/2017         32     -99999      Rain
5  01/06/2017          31         2     Sunny
6  01/06/2017          34         5  No Event

In [18]:
# Creating a DataFrame

df = pd.DataFrame({
    'Score' : ['exceptional','avg','good','poor','avg','exceptional'],
    'Student' : ['rob','maya','parthiv','tom','julian','erica']
})

df

         Score  Student
0  exceptional      rob
1          avg     maya
2         good  parthiv
3         poor      tom
4          avg   julian
5  exceptional    erica

In [19]:
# Replacing List of values with another list of values :

df.replace(["exceptional","good","avg","poor"],[1,2,3,4])

   Score  Student
0      1      rob
1      3     maya
2      2  parthiv
3      4      tom
4      3   julian
5      1    erica